/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device */
        get: operations["device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Device */
        patch: operations["patch_device_api_v1_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/devices/{device_id}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_api_v1_devices__device_id__current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calibrate
         * @description §8.4 오프셋. 이후 수신분부터 적용된다.
         */
        post: operations["calibrate_api_v1_devices__device_id__calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series */
        get: operations["series_api_v1_devices__device_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_devices__device_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_v1_devices__device_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vapid Public Key */
        get: operations["vapid_public_key_api_v1_push_vapid_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe */
        post: operations["subscribe_api_v1_push_subscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Calibration */
        Calibration: {
            /**
             * T Air
             * @default 0
             */
            t_air: number;
            /**
             * Rh
             * @default 0
             */
            rh: number;
            /**
             * T Surf
             * @default 0
             */
            t_surf: number;
        };
        /**
         * Current
         * @description GET current 응답이자 WS 'reading' 메시지 본문.
         */
        Current: {
            /** Device Id */
            device_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "SAFE" | "WATCH" | "ALERT" | "CONDENSING" | "STALE";
            forecast: components["schemas"]["Forecast"] | null;
            /** Probes */
            probes: components["schemas"]["ProbeReading"][];
        };
        /** Device */
        Device: {
            /** Id */
            id: string;
            /** Home Id */
            home_id: string;
            /** Label */
            label: string | null;
            /** Location Tag */
            location_tag: string | null;
            /** Fw */
            fw: string | null;
            /** Last Seen */
            last_seen: string | null;
            /** Online */
            online: boolean | null;
            /** Calib T Air */
            calib_t_air: number;
            /** Calib Rh */
            calib_rh: number;
            /** Calib T Surf */
            calib_t_surf: number;
            /**
             * State
             * @enum {string}
             */
            state: "SAFE" | "WATCH" | "ALERT" | "CONDENSING" | "STALE";
        };
        /** DevicePatch */
        DevicePatch: {
            /** Label */
            label?: string | null;
            /** Location Tag */
            location_tag?: string | null;
        };
        /** Diagnostic */
        Diagnostic: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** F Rsi */
            f_rsi: number | null;
            /** Tdr */
            tdr: number | null;
            /** T Ext Avg */
            t_ext_avg: number | null;
            /** Minutes Alert */
            minutes_alert: number;
            /** Mould Dose */
            mould_dose: number;
        };
        /** Event */
        Event: {
            /** Id */
            id: number;
            /**
             * State
             * @enum {string}
             */
            state: "SAFE" | "WATCH" | "ALERT" | "CONDENSING" | "STALE";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Peak Rh Surf */
            peak_rh_surf: number | null;
            /** Min Delta T */
            min_delta_t: number | null;
        };
        /** Forecast */
        Forecast: {
            /** Target */
            target: number;
            /** Hours Low */
            hours_low: number;
            /** Hours High */
            hours_high: number;
            /** Slope */
            slope: number;
            /** R2 */
            r2: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProbeReading */
        ProbeReading: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Probe Id */
            probe_id: string;
            /** T Air */
            t_air: number;
            /** Rh */
            rh: number;
            /** T Surf */
            t_surf: number;
            /** T Dew */
            t_dew: number;
            /** T80 */
            t80: number;
            /** Rh Surf */
            rh_surf: number;
        };
        /** PushSubscription */
        PushSubscription: {
            /** Endpoint */
            endpoint: string;
            /** Keys */
            keys: {
                [key: string]: string;
            };
            /**
             * Quiet Start
             * @default 23
             */
            quiet_start: number;
            /**
             * Quiet End
             * @default 7
             */
            quiet_end: number;
        };
        /** Report */
        Report: {
            device: components["schemas"]["Device"];
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
            /** Minutes Alert */
            minutes_alert: number;
            /** Minutes Condensing */
            minutes_condensing: number;
            /** Event Days */
            event_days: string[];
            /** Mean Rh Surf */
            mean_rh_surf: number | null;
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Weather Sources */
            weather_sources: {
                [key: string]: number;
            };
        };
        /** ReportRequest */
        ReportRequest: {
            /** Device Id */
            device_id: string;
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_device_api_v1_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_api_v1_devices__device_id__current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Current"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_api_v1_devices__device_id__calibration_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Calibration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_api_v1_devices__device_id__series_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                bucket?: "raw" | "1m" | "1h" | "1d";
            };
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeReading"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_devices__device_id__events_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_v1_devices__device_id__diagnostics_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vapid_public_key_api_v1_push_vapid_public_key_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_api_v1_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscription"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
